課題2のレビューをお願いします
Tkam13/quelcode pull request #2
Opened 2020-03-02 07:21 UTC by Tkam13

#markup_kadai_02.htmlについてレビューをお願いします

##やったこと
- 0c01c8b 大体の内容を作りました
- 590207c スケジュールの時間を太字にしました
- a82bf24 langをjaに修正しました

2020-03-03 04:19 UTC, fjtawork reviewed
講師の藤田です。
コメントしました！

2020-03-03 04:19 UTC, fjtawork commented on practice2/markup_kadai_02.html
> +       <td><b>11:00-13:00</b></td>
bタグは使わずCSSで太文字にするのが一般的ですね

2020-03-06 07:10 UTC, Tkam13 commented
c32572d このコミットでcssで太文字にしました

2020-03-06 08:28 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-06 08:28 UTC, piasoratech commented on practice1/markup_kadai_01.html
> +    <div class="sender-column">
`main`タグの開始はここからです。(`body`のすぐ下)

2020-03-06 08:28 UTC, piasoratech commented on practice1/markup_kadai_01.html
> +            Email: kaito@quelcode.com
ここは各行に`p`タグを指定して下さい。
お手本のPDFと表示が異なってしまいますが気にしなくて大丈夫です。

2020-03-06 08:28 UTC, piasoratech commented on practice1/markup_kadai_01.html
> +            恵比寿ガーデンプレイス
ここも同様に各行に`p`タグを使用して下さい

2020-03-06 08:28 UTC, piasoratech commented on practice1/markup_kadai_01.html
>          <h1>Re:QUELCODE大学の科学部参加の件</h1>
`section`タグを使用しましょう

2020-03-06 08:28 UTC, piasoratech commented on practice1/markup_kadai_01.html
> +            いつでも私たちと一緒に勉強を始めていただけます。しかし、学期の初めから始めることができればより良いでしょう。それぞれの開始日は次のとおりです。
文章にはなにかしらのタグを使用して下さい。

2020-03-06 08:28 UTC, piasoratech commented on practice2/markup_kadai_02.html
> +  <h1>X期受講予定のみなさまへ</h1>
`body`タグの下に`main`タグを使用して、`main`タグの下に`section`タグを使用しましょう
タグの意味も併せてカリキュラムを読んだり検索したりして確認して下さい。

2020-03-06 08:28 UTC, piasoratech commented on practice2/markup_kadai_2.txt
> +<!-- ここから下は変更しないでください -->
課題のテキストファイルは提出ファイルに含めなくて大丈夫です。

2020-03-06 08:28 UTC, piasoratech commented on practice2/markup_kadai_02.html
> +    当日までにご用意いただきたいもの
なにかしらのタグを使用しましょう

2020-03-06 09:38 UTC, Tkam13 commented
b8fce37 で指摘事項の修正を行いました、よろしくお願いします。

2020-03-06 09:43 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-06 09:43 UTC, piasoratech commented on practice2/markup_kadai_02.html
> +  <main>
ここ直っていないので直しましょう！

2020-03-08 12:28 UTC, Tkam13 commented
ff0330c で最初の部分にsectionタグを追加しました。

2020-03-09 05:53 UTC, piasoratech requested changes
確認しました
OKです！

2020-03-09 07:19 UTC, merged